### PR TITLE
35346

### PR DESCRIPTION
**Pull request by ark43420**
dbClasses中主要的是sdb 数据库和集群相关功能的实现，在代码中直接使用了大量的spider monkey接口，导致一些问题： 
1、实际业务实现与第三方库耦合严重，如果切换别的第三方库业务逻辑需要大幅改动。 
2、业务功能实现需要过多关心第三方库的接口，了解第三方库的接口许多用法。 
3、有很多类似于获取参数与返回参数等步骤是类似的，在dbClasses中需要重复很多类似逻辑。 

当前spt已经抽象出一套新框架，整个过程业务开发者基本基本只需要关注本身业务功能的开发，无需关注js引擎的接口。 
除此之外，新增的help功能与js的报错信息都依赖新框架，没有迁移前的dbClasses的对象都缺少这些功能。 

将dbClasses代码迁移后，代码将更好维护。也补足了缺失的spt help()功能及优化了功能出错时报出的错误信息。

### CODE REVIEW

**Comment by OliverFinn** [comment]
请设计

**Comment by OliverFinn** [comment]
按story 来设计吧

**Comment by ark43420** [comment]
【Story设计】 
设计文档：03.开发设计/JS对象增强和远程化-dbClasses新引擎迁移.docx

**Comment by ark43420** [comment]
Story检视通过，开始开发

**Comment by ark43420** [comment]
C++驱动已提交
【提交记录】 
trunk: 
Revision: 35345 
Author: wujiaming 
Date: 2018年4月19日 22:48:22 
Message: 
SEQUOIADBMAINSTREAM-2760 【Story】dbClasses新引擎迁移 
---- 
Modified : /trunk/SequoiaDB/engine/SConscriptFmp 
Modified : /trunk/SequoiaDB/engine/SConscriptShell 
Modified : /trunk/SequoiaDB/engine/SConscriptTool 
Modified : /trunk/SequoiaDB/engine/bson/bson-inl.h 
Modified : /trunk/SequoiaDB/engine/client/client.hpp 
Modified : /trunk/SequoiaDB/engine/client/clientImpl.hpp 
Modified : /trunk/SequoiaDB/engine/client/clientcpp.cpp 
Modified : /trunk/SequoiaDB/engine/include/fmpDef.h 
Modified : /trunk/SequoiaDB/engine/include/fmpJSVM.hpp 
Modified : /trunk/SequoiaDB/engine/include/spd.h 
Modified : /trunk/SequoiaDB/engine/include/sptApi.hpp 
Modified : /trunk/SequoiaDB/engine/include/sptArguments.hpp 
Modified : /trunk/SequoiaDB/engine/include/sptCommon.hpp 
Modified : /trunk/SequoiaDB/engine/include/sptConvertor.hpp 
Modified : /trunk/SequoiaDB/engine/include/sptConvertorHelper.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBBinData.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBCL.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBCS.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBCount.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBCursor.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBDC.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBDate.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBDomain.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBMaxKey.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBMinKey.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBNode.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBNumberDecimal.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBNumberLong.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBOID.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBQuery.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBRG.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBRegex.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBSdb.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBSecureSdb.hpp 
Added : /trunk/SequoiaDB/engine/include/sptDBTimestamp.hpp 
Modified : /trunk/SequoiaDB/engine/include/sptInjection.hpp 
Modified : /trunk/SequoiaDB/engine/include/sptInvoker.hpp 
Modified : /trunk/SequoiaDB/engine/include/sptObjDesc.hpp 
Modified : /trunk/SequoiaDB/engine/include/sptReturnVal.hpp 
Modified : /trunk/SequoiaDB/engine/include/sptSPArguments.hpp 
Modified : /trunk/SequoiaDB/engine/include/sptSPDef.hpp 
Modified : /trunk/SequoiaDB/engine/pmd/fmpJSVM.cpp 
Modified : /trunk/SequoiaDB/engine/spd/spdSession.cpp 
Added : /trunk/SequoiaDB/engine/spt/db 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBBinData.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBCL.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBCS.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBCount.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBCursor.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBDC.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBDate.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBDomain.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBMaxKey.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBMinKey.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBNode.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBNumberDecimal.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBNumberLong.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBOID.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBQuery.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBRG.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBRegex.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBSdb.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBSecureSdb.cpp 
Added : /trunk/SequoiaDB/engine/spt/db/sptDBTimestamp.cpp 
Modified : /trunk/SequoiaDB/engine/spt/help.js 
Modified : /trunk/SequoiaDB/engine/spt/sdb.js 
Modified : /trunk/SequoiaDB/engine/spt/sptContainer.cpp 
Modified : /trunk/SequoiaDB/engine/spt/sptConvertor.cpp 
Modified : /trunk/SequoiaDB/engine/spt/sptConvertorHelper.cpp 
Modified : /trunk/SequoiaDB/engine/spt/sptInvoker.cpp 
Modified : /trunk/SequoiaDB/engine/spt/sptObjDesc.cpp 
Modified : /trunk/SequoiaDB/engine/spt/sptReturnVal.cpp 
Modified : /trunk/SequoiaDB/engine/spt/sptSPArguments.cpp 
Modified : /trunk/SequoiaDB/engine/spt/sptSPScope.cpp 

Revision: 35346 
Author: wujiaming 
Date: 2018年4月19日 22:51:30 
Message: 
SEQUOIADBMAINSTREAM-2760 【Story】dbClasses新引擎迁移 参数错误时返回错误码，需修改对应用例 
---- 
Modified : /trunk/testcase_new/story/js/domain/domain_8116.js 
Modified : /trunk/testcase_new/story/js/idIndex/commlib.js 
Modified : /trunk/testcase_new/story/js/idIndex/idIndex_5580.js 
Modified : /trunk/testcase_new/story/js/jsonTypes/minmaxkeyErrPara_5388.js 
Modified : /trunk/testcase_new/story/js/lob/lob_anomaly_getLob_13902_13903.js 
Modified : /trunk/testcase_new/story/js/lob/lob_anomaly_putLob_13913.js 
Modified : /trunk/testcase_new/story/js/procedures/procedure_8193.js 
Modified : /trunk/testcase_new/story/js/procedures/procedure_9927.js 

Revision: 35347 
Author: wujiaming 
Date: 2018年4月19日 23:09:21 
Message: 
SEQUOIADBMAINSTREAM-2760 【Story】dbClasses新引擎迁移 补充漏提交文件 
---- 
Added : /trunk/SequoiaDB/engine/include/sptObject.hpp 
Added : /trunk/SequoiaDB/engine/include/sptSPObject.hpp 
Added : /trunk/SequoiaDB/engine/spt/sptSPObject.cpp 

Revision: 35348 
Author: wujiaming 
Date: 2018年4月19日 23:47:48 
Message: 
fix bug: 驱动不应该忽略SDB_DMS_EOC错误 
---- 
Modified : /trunk/SequoiaDB/engine/client/clientcpp.cpp 



【CheckList】 
检查项---------------------------------------------------------结论（NA/N/Y） 
-------------------------------------------------------------------------------------------- 
修改代码是否全部提交SVN主干和分支版本 
且符合代码规范--------------------------------------------仅主干 
是否用例全部通过-----------------------------------------Y 
修改代码是否通过检视------------------------------------N 
资料是否变更-----------------------------------------------NA 
接口是否变更-----------------------------------------------NA 
相关驱动是否变更或添加---------------------------------NA 
是否保持向前兼容------------------------------------------Y 
是否影响安装部署和监控---------------------------------NA 
是否影响性能-----------------------------------------------NA 
sdb shell帮助信息是否更新------------------------------NA

已完成，请处理

**Comment by ark43420** [comment]
已完成，请处理

**Comment by OliverFinn** [comment]
请安排测试

**Comment by ark43420** [comment]
1. 本story在SEQUOIADBMAINSTREAM****中已经测试设计完成，并有完整的文本用例。但当时由于开发进度原因，仅执行了C++驱动修改部分，未执行JS修改部分。 
2. JS用例自动化现已完成。新增问题均有问题单跟踪。已根据JS部分的测试情况更新测试报告。

【测试结果】 
测试通过 
【测试版本】 
SequoiaDB version: 3.0 
Release: 36143 
2018-07-16-00.35.56(Enterprise-Debug) 
【测试用例】 
TestLink: sequoiaDB -> story功能测试 -> dbClasses引擎迁移 
svn: /trunk/testcase_new/story/js/dbClasses 
【测试报告】 
trunk\internal_doc\06.测试报告\story测试报告\Story-dbClasses引擎迁移测试报告.doc

**Pull request closed without merging**
